// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/clap.proto

package clap_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CLAPEmbedder_GetEmbedding_FullMethodName     = "/clap.CLAPEmbedder/GetEmbedding"
	CLAPEmbedder_GetTextEmbedding_FullMethodName = "/clap.CLAPEmbedder/GetTextEmbedding"
)

// CLAPEmbedderClient is the client API for CLAPEmbedder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CLAPEmbedder defines the gRPC contract between the Go orchestrator
// and the Python neural inference sidecar.
type CLAPEmbedderClient interface {
	GetEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
	GetTextEmbedding(ctx context.Context, in *TextEmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
}

type cLAPEmbedderClient struct {
	cc grpc.ClientConnInterface
}

func NewCLAPEmbedderClient(cc grpc.ClientConnInterface) CLAPEmbedderClient {
	return &cLAPEmbedderClient{cc}
}

func (c *cLAPEmbedderClient) GetEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, CLAPEmbedder_GetEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLAPEmbedderClient) GetTextEmbedding(ctx context.Context, in *TextEmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, CLAPEmbedder_GetTextEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CLAPEmbedderServer is the server API for CLAPEmbedder service.
// All implementations must embed UnimplementedCLAPEmbedderServer
// for forward compatibility.
//
// CLAPEmbedder defines the gRPC contract between the Go orchestrator
// and the Python neural inference sidecar.
type CLAPEmbedderServer interface {
	GetEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	GetTextEmbedding(context.Context, *TextEmbeddingRequest) (*EmbeddingResponse, error)
	mustEmbedUnimplementedCLAPEmbedderServer()
}

// UnimplementedCLAPEmbedderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCLAPEmbedderServer struct{}

func (UnimplementedCLAPEmbedderServer) GetEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmbedding not implemented")
}
func (UnimplementedCLAPEmbedderServer) GetTextEmbedding(context.Context, *TextEmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTextEmbedding not implemented")
}
func (UnimplementedCLAPEmbedderServer) mustEmbedUnimplementedCLAPEmbedderServer() {}
func (UnimplementedCLAPEmbedderServer) testEmbeddedByValue()                      {}

// UnsafeCLAPEmbedderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CLAPEmbedderServer will
// result in compilation errors.
type UnsafeCLAPEmbedderServer interface {
	mustEmbedUnimplementedCLAPEmbedderServer()
}

func RegisterCLAPEmbedderServer(s grpc.ServiceRegistrar, srv CLAPEmbedderServer) {
	// If the following call panics, it indicates UnimplementedCLAPEmbedderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CLAPEmbedder_ServiceDesc, srv)
}

func _CLAPEmbedder_GetEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLAPEmbedderServer).GetEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLAPEmbedder_GetEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLAPEmbedderServer).GetEmbedding(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLAPEmbedder_GetTextEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLAPEmbedderServer).GetTextEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLAPEmbedder_GetTextEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLAPEmbedderServer).GetTextEmbedding(ctx, req.(*TextEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CLAPEmbedder_ServiceDesc is the grpc.ServiceDesc for CLAPEmbedder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CLAPEmbedder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clap.CLAPEmbedder",
	HandlerType: (*CLAPEmbedderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmbedding",
			Handler:    _CLAPEmbedder_GetEmbedding_Handler,
		},
		{
			MethodName: "GetTextEmbedding",
			Handler:    _CLAPEmbedder_GetTextEmbedding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/clap.proto",
}
