// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/clap.proto

package clap_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbeddingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw float32 PCM audio bytes, flat-packed in little-endian.
	PcmData []byte `protobuf:"bytes,1,opt,name=pcm_data,json=pcmData,proto3" json:"pcm_data,omitempty"`
	// Sample rate of the audio. LAION-CLAP strictly requires 48000 Hz.
	SampleRate    int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_proto_clap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_proto_clap_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingRequest) GetPcmData() []byte {
	if x != nil {
		return x.PcmData
	}
	return nil
}

func (x *EmbeddingRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_proto_clap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_proto_clap_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type TextEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextEmbeddingRequest) Reset() {
	*x = TextEmbeddingRequest{}
	mi := &file_proto_clap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEmbeddingRequest) ProtoMessage() {}

func (x *TextEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*TextEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_proto_clap_proto_rawDescGZIP(), []int{2}
}

func (x *TextEmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_proto_clap_proto protoreflect.FileDescriptor

const file_proto_clap_proto_rawDesc = "" +
	"\n" +
	"\x10proto/clap.proto\x12\x04clap\"N\n" +
	"\x10EmbeddingRequest\x12\x19\n" +
	"\bpcm_data\x18\x01 \x01(\fR\apcmData\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\"1\n" +
	"\x11EmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\"*\n" +
	"\x14TextEmbeddingRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2\x98\x01\n" +
	"\fCLAPEmbedder\x12?\n" +
	"\fGetEmbedding\x12\x16.clap.EmbeddingRequest\x1a\x17.clap.EmbeddingResponse\x12G\n" +
	"\x10GetTextEmbedding\x12\x1a.clap.TextEmbeddingRequest\x1a\x17.clap.EmbeddingResponseBKZIgithub.com/johnarleyburns/parso-ia-music-indexer/internal/clap/clap_protob\x06proto3"

var (
	file_proto_clap_proto_rawDescOnce sync.Once
	file_proto_clap_proto_rawDescData []byte
)

func file_proto_clap_proto_rawDescGZIP() []byte {
	file_proto_clap_proto_rawDescOnce.Do(func() {
		file_proto_clap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clap_proto_rawDesc), len(file_proto_clap_proto_rawDesc)))
	})
	return file_proto_clap_proto_rawDescData
}

var file_proto_clap_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_clap_proto_goTypes = []any{
	(*EmbeddingRequest)(nil),     // 0: clap.EmbeddingRequest
	(*EmbeddingResponse)(nil),    // 1: clap.EmbeddingResponse
	(*TextEmbeddingRequest)(nil), // 2: clap.TextEmbeddingRequest
}
var file_proto_clap_proto_depIdxs = []int32{
	0, // 0: clap.CLAPEmbedder.GetEmbedding:input_type -> clap.EmbeddingRequest
	2, // 1: clap.CLAPEmbedder.GetTextEmbedding:input_type -> clap.TextEmbeddingRequest
	1, // 2: clap.CLAPEmbedder.GetEmbedding:output_type -> clap.EmbeddingResponse
	1, // 3: clap.CLAPEmbedder.GetTextEmbedding:output_type -> clap.EmbeddingResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_clap_proto_init() }
func file_proto_clap_proto_init() {
	if File_proto_clap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clap_proto_rawDesc), len(file_proto_clap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clap_proto_goTypes,
		DependencyIndexes: file_proto_clap_proto_depIdxs,
		MessageInfos:      file_proto_clap_proto_msgTypes,
	}.Build()
	File_proto_clap_proto = out.File
	file_proto_clap_proto_goTypes = nil
	file_proto_clap_proto_depIdxs = nil
}
