# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import clap_pb2 as clap__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in clap_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CLAPEmbedderStub:
    """CLAPEmbedder defines the gRPC contract between the Go orchestrator
    and the Python neural inference sidecar.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmbedding = channel.unary_unary(
                '/clap.CLAPEmbedder/GetEmbedding',
                request_serializer=clap__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=clap__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.GetTextEmbedding = channel.unary_unary(
                '/clap.CLAPEmbedder/GetTextEmbedding',
                request_serializer=clap__pb2.TextEmbeddingRequest.SerializeToString,
                response_deserializer=clap__pb2.EmbeddingResponse.FromString,
                _registered_method=True)


class CLAPEmbedderServicer:
    """CLAPEmbedder defines the gRPC contract between the Go orchestrator
    and the Python neural inference sidecar.
    """

    def GetEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTextEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CLAPEmbedderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=clap__pb2.EmbeddingRequest.FromString,
                    response_serializer=clap__pb2.EmbeddingResponse.SerializeToString,
            ),
            'GetTextEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTextEmbedding,
                    request_deserializer=clap__pb2.TextEmbeddingRequest.FromString,
                    response_serializer=clap__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clap.CLAPEmbedder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clap.CLAPEmbedder', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CLAPEmbedder:
    """CLAPEmbedder defines the gRPC contract between the Go orchestrator
    and the Python neural inference sidecar.
    """

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clap.CLAPEmbedder/GetEmbedding',
            clap__pb2.EmbeddingRequest.SerializeToString,
            clap__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTextEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clap.CLAPEmbedder/GetTextEmbedding',
            clap__pb2.TextEmbeddingRequest.SerializeToString,
            clap__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
